_instantiator: pytorch_lightning.cli.instantiate_module
base_optimizer_name: adamw
batch_size: 64
betas:
- 0.9
- 0.999
cov_mat: true
cutmix_alpha: 0.0
dataset: cifar100
epsilon: 0.01
erase_prob: 0.0
flip_prob: 0.5
from_scratch: false
image_size: 224
label_smoothing: 0.1
lora_alpha: 8
lora_bias: none
lora_dropout: 0.0
lora_r: 8
lora_target_modules:
- query
- value
lr: 0.001
max_num_models: 20
max_scale: 1.0
min_scale: 0.08
mix_prob: 1.0
mixup_alpha: 0.0
model_name: vit-b16-224-dino
momentum: 0.9
n_classes: 100
num_classes: null
num_particles: 4
optimizer: fhbi
rand_aug_m: 9
rand_aug_n: 0
rho: 1.0e-05
root: /vast/hvp2011/t/vtab-1k/cifar100
scheduler: cosine
sigma: 1.2
size: 224
training_mode: lora
transform_train_id: 0
use_sam: false
use_trivial_aug: false
warmup_steps: 500
weight_decay: 0.5
weights: null
weights_path: checkpoint/B_16.pth
workers: 4
